In [82]:
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv
import requests
import json

In [55]:
df_restaurantes = pd.read_csv("data/restaurantes_chiara_mal.csv")
df_restaurantes

,Unnamed: 0,Nombre,Descripcion,Tipo de lugar,Dirección,Municipio,Provincia,Entorno,Email,Teléfono,...,Nivel precio,Michelin,Repsol,lat,lon,valoracion,num_resenas,url_imagen,Active,Patrocinado
0,0,Agorregi,"El restaurante Agorregi, ubicado en el barrio ...",restaurantes,NaN,San Sebastián,Guipúzcoa,"Costa Vasca,San Sebastián",agorregi@agorregi.com,943 22 43 28,...,Moderado,NaN,NaN,43.302405,-2.011846,4.6,571.0,https://places.googleapis.com/v1/places/ChIJFT...,1,0
1,1,Aizian,Este moderno y acogedor restaurante fue diseña...,restaurantes,NaN,Bilbao,Vizcaya,Bilbao,aizian@restaurante-aizian.com,944 28 00 39,...,Moderado,NaN,NaN,43.267519,-2.941807,4.7,435.0,https://places.googleapis.com/v1/places/ChIJde...,1,0
2,2,Akelarre,Pedro Subijana desarrolla desde 1970 una cocin...,restaurantes,NaN,San Sebastián,Guipúzcoa,San Sebastián,restaurante@akelarre.net,943 31 12 09,...,Muy caro,NaN,NaN,43.307750,-2.043135,4.5,1925.0,https://places.googleapis.com/v1/places/ChIJXd...,1,0
3,3,Alameda,La tercera generación es quien está a cargo de...,restaurantes,NaN,Hondarribia,Guipúzcoa,Costa Vasca,info@restaurantealameda.net,943 64 27 89,...,Caro,NaN,NaN,43.361242,-1.792691,4.6,1098.0,https://places.googleapis.com/v1/places/ChIJfb...,1,0
4,4,Almiketxu,Es un caserío típico vasco y está regentado po...,restaurantes,NaN,Bermeo,Vizcaya,Costa Vasca,almiketxu@gmail.com,946 88 09 25,...,Caro,NaN,NaN,43.408905,-2.734229,4.6,1924.0,https://places.googleapis.com/v1/places/ChIJZ5...,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,765,Quesería Soloitza,Quesería Soloitza,"queseria, tiendas",NaN,Ayala,Álava,Montes y Valles vascos,info@soloitza.com,635 71 84 75,...,NaN,NaN,NaN,43.092827,-3.048182,5.0,45.0,https://places.googleapis.com/v1/places/ChIJmY...,1,0
486,767,Larrañaga Gozotegia,Repostería tradicional. De su obrador salen l...,tiendas,NaN,Bergara,Guipúzcoa,Montes y Valles vascos,NaN,943 76 10 51,...,NaN,NaN,NaN,43.116464,-2.412943,4.6,70.0,https://places.googleapis.com/v1/places/ChIJLe...,1,0
487,772,Pastelería Sosoaga,"La pastelería López Sosoaga, abierta en 1868 p...",tiendas,NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 25 85 73,...,NaN,NaN,NaN,42.842886,-2.668233,4.3,186.0,https://places.googleapis.com/v1/places/ChIJ1w...,1,0
488,773,Pastelería La Peña Dulce,La Peña Dulce es una de las pastelerías de may...,tiendas,NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 13 26 37,...,NaN,NaN,NaN,42.851866,-2.673002,4.2,106.0,https://places.googleapis.com/v1/places/ChIJVc...,1,0
489,775,Martina Zuricalday,NaN,tiendas,NaN,Bilbao,Vizcaya,Bilbao,NaN,944 43 57 96,...,Moderado,NaN,NaN,43.258907,-2.943496,4.2,372.0,https://places.googleapis.com/v1/places/ChIJsX...,1,0

In [57]:
df_tiendas = pd.read_csv("data/zonas_compras_limpio.csv")
df_tiendas

,documentname,documentdescription,locality,marks,municipality,friendlyurl,tourismemail,web,productclub,buytype,qualityassurance,lon,lat,provincia
0,Ezkur - Txerri,NaN,Getaria,Costa Vasca,Getaria,https://turismoa.euskadi.eus/es/productores-al...,NaN,http://www.ezkurtxerri.com,1.0,Agricultura Ecológica,NaN,-2.209715,43.280314,Gipuzkoa
1,Garoa,Queseria tradicional elaboradora de queso Idia...,Zerain,Montes y Valles vascos,Zerain,https://turismoa.euskadi.eus/es/queserias/garo...,NaN,NaN,1.0,Eusko Label,NaN,-2.270865,43.010814,Gipuzkoa
2,Gazi Gozo,Tienda de productos Gourmet de la tierra y de ...,Lazkao,Montes y Valles vascos,Lazkao,https://turismoa.euskadi.eus/es/tiendas-gourme...,NaN,http://www.gazigozo.com/,1.0,Postres,NaN,-2.186601,43.033653,Gipuzkoa
3,Gaztaindizar,NaN,Zarautz,Costa Vasca,Zarautz,https://turismoa.euskadi.eus/es/productores-al...,NaN,NaN,1.0,Agricultura Ecológica,NaN,-2.157662,43.269050,Gipuzkoa
4,Mahala Naturala,NaN,Leaburu,Montes y Valles vascos,Leaburu,https://turismoa.euskadi.eus/es/productores-al...,info@mahala.eus,http://mahala.eus/,1.0,Agricultura Ecológica,NaN,-2.047884,43.122757,Gipuzkoa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,Real Sociedad (tienda Anoeta),Real Sociedad (tienda Anoeta),NaN,San Sebastián,Donostia / San Sebastián,https://turismoa.euskadi.eus/es/tiendas-gourme...,rsstore@realsociedad.eus,https://rsstore.realsociedad.eus/es/,NaN,Pescados y Mariscos,NaN,-1.973587,43.301367,Gipuzkoa
123,Real Sociedad (tienda Elkano),Real Sociedad (tienda Elkano),NaN,San Sebastián,Donostia / San Sebastián,https://turismoa.euskadi.eus/es/tiendas-gourme...,NaN,NaN,NaN,Pescados y Mariscos,NaN,-1.983323,43.321874,Gipuzkoa
124,Burutxaga Hestebeteak,Burutxaga Hestebeteak,NaN,Montes y Valles vascos,Amurrio,https://turismoa.euskadi.eus/es/tiendas-gourme...,burutxaga.hestebeteak@gmail.com,NaN,NaN,Agricultura Ecológica,NaN,-3.004257,43.039381,Araba/Álava
125,Quesería Soloitza,Quesería Soloitza,Arespalditza/Respaldiza | Diseminado,Montes y Valles vascos,Ayala/Aiara,https://turismoa.euskadi.eus/es/tiendas-gourme...,info@soloitza.com,https://soloitza.com/,NaN,Eusko Label,NaN,-3.048182,43.092827,Araba/Álava
126,Jo Topagunea,Jo Topagunea,NaN,Montes y Valles vascos,Tolosa,https://turismoa.euskadi.eus/es/tiendas-gourme...,jotopagunea@gmail.com,NaN,NaN,Postres,NaN,-2.072194,43.138965,Gipuzkoa

In [58]:
# concatenamos buytype de df_tiendas en Tipo comida sin reducir el dataset de restaurantes
n_rows_before = len(df_restaurantes)

buytype_lookup = (
    df_tiendas[["documentname", "buytype"]]
    .dropna(subset=["documentname"])
)
buytype_lookup["documentname"] = buytype_lookup["documentname"].astype(str).str.strip()
buytype_lookup = (
    buytype_lookup.groupby("documentname", as_index=False)["buytype"]
    .agg(lambda s: " | ".join(dict.fromkeys(str(v).strip() for v in s if pd.notna(v) and str(v).strip())))
)

def concat_unique_types(tipo_actual, tipo_nuevo):
    values = []
    for value in [tipo_actual, tipo_nuevo]:
        if pd.isna(value):
            continue
        for part in str(value).split("|"):
            clean = part.strip()
            if clean and clean not in values:
                values.append(clean)
    return " | ".join(values) if values else pd.NA

def concat_unique_places(place_actual, place_new):
    values = []
    seen = set()
    for value in [place_actual, place_new]:
        if pd.isna(value):
            continue
        for part in str(value).replace("|", ",").split(","):
            clean = part.strip()
            key = clean.lower()
            if clean and key not in seen:
                values.append(clean)
                seen.add(key)
    return ", ".join(values) if values else pd.NA

# left merge: conserva todas las filas de df_restaurantes
df_restaurantes = df_restaurantes.merge(
    buytype_lookup.rename(columns={"documentname": "Nombre", "buytype": "buytype_match"}),
    on="Nombre",
    how="left"
 )

# solo concatenamos en filas comunes (donde hay match)
mask_match = df_restaurantes["buytype_match"].notna()
df_restaurantes.loc[mask_match, "Tipo comida"] = df_restaurantes.loc[mask_match].apply(
    lambda row: concat_unique_types(row.get("Tipo comida"), row.get("buytype_match")),
    axis=1
)

has_tienda = df_restaurantes["Tipo de lugar"].fillna("").str.lower().str.contains(r"\btienda(?:s)?\b", regex=True)
df_restaurantes.loc[mask_match & ~has_tienda, "Tipo de lugar"] = df_restaurantes.loc[
    mask_match & ~has_tienda, "Tipo de lugar"
].apply(lambda x: concat_unique_places(x, "tienda"))

df_restaurantes.drop(columns=["buytype_match"], inplace=True)

n_rows_after = len(df_restaurantes)
if n_rows_after != n_rows_before:
    raise ValueError(f"El dataset se redujo de {n_rows_before} a {n_rows_after} filas")

In [59]:
df_restaurantes

,Unnamed: 0,Nombre,Descripcion,Tipo de lugar,Dirección,Municipio,Provincia,Entorno,Email,Teléfono,...,Nivel precio,Michelin,Repsol,lat,lon,valoracion,num_resenas,url_imagen,Active,Patrocinado
0,0,Agorregi,"El restaurante Agorregi, ubicado en el barrio ...",restaurantes,NaN,San Sebastián,Guipúzcoa,"Costa Vasca,San Sebastián",agorregi@agorregi.com,943 22 43 28,...,Moderado,NaN,NaN,43.302405,-2.011846,4.6,571.0,https://places.googleapis.com/v1/places/ChIJFT...,1,0
1,1,Aizian,Este moderno y acogedor restaurante fue diseña...,restaurantes,NaN,Bilbao,Vizcaya,Bilbao,aizian@restaurante-aizian.com,944 28 00 39,...,Moderado,NaN,NaN,43.267519,-2.941807,4.7,435.0,https://places.googleapis.com/v1/places/ChIJde...,1,0
2,2,Akelarre,Pedro Subijana desarrolla desde 1970 una cocin...,restaurantes,NaN,San Sebastián,Guipúzcoa,San Sebastián,restaurante@akelarre.net,943 31 12 09,...,Muy caro,NaN,NaN,43.307750,-2.043135,4.5,1925.0,https://places.googleapis.com/v1/places/ChIJXd...,1,0
3,3,Alameda,La tercera generación es quien está a cargo de...,restaurantes,NaN,Hondarribia,Guipúzcoa,Costa Vasca,info@restaurantealameda.net,943 64 27 89,...,Caro,NaN,NaN,43.361242,-1.792691,4.6,1098.0,https://places.googleapis.com/v1/places/ChIJfb...,1,0
4,4,Almiketxu,Es un caserío típico vasco y está regentado po...,restaurantes,NaN,Bermeo,Vizcaya,Costa Vasca,almiketxu@gmail.com,946 88 09 25,...,Caro,NaN,NaN,43.408905,-2.734229,4.6,1924.0,https://places.googleapis.com/v1/places/ChIJZ5...,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,765,Quesería Soloitza,Quesería Soloitza,"queseria, tiendas",NaN,Ayala,Álava,Montes y Valles vascos,info@soloitza.com,635 71 84 75,...,NaN,NaN,NaN,43.092827,-3.048182,5.0,45.0,https://places.googleapis.com/v1/places/ChIJmY...,1,0
486,767,Larrañaga Gozotegia,Repostería tradicional. De su obrador salen l...,tiendas,NaN,Bergara,Guipúzcoa,Montes y Valles vascos,NaN,943 76 10 51,...,NaN,NaN,NaN,43.116464,-2.412943,4.6,70.0,https://places.googleapis.com/v1/places/ChIJLe...,1,0
487,772,Pastelería Sosoaga,"La pastelería López Sosoaga, abierta en 1868 p...",tiendas,NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 25 85 73,...,NaN,NaN,NaN,42.842886,-2.668233,4.3,186.0,https://places.googleapis.com/v1/places/ChIJ1w...,1,0
488,773,Pastelería La Peña Dulce,La Peña Dulce es una de las pastelerías de may...,tiendas,NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 13 26 37,...,NaN,NaN,NaN,42.851866,-2.673002,4.2,106.0,https://places.googleapis.com/v1/places/ChIJVc...,1,0
489,775,Martina Zuricalday,NaN,tiendas,NaN,Bilbao,Vizcaya,Bilbao,NaN,944 43 57 96,...,Moderado,NaN,NaN,43.258907,-2.943496,4.2,372.0,https://places.googleapis.com/v1/places/ChIJsX...,1,0

## RESTAURANTES

In [61]:
import re
import unicodedata
import requests

n_rows_before = len(df_restaurantes)
url = "https://opendata.euskadi.eus/contenidos/ds_recursos_turisticos/restaurantes_sidrerias_bodegas/opendata/restaurantes.geojson"

resp = requests.get(url, timeout=30)
resp.raise_for_status()
geojson_data = resp.json()

properties = pd.json_normalize([f.get("properties", {}) for f in geojson_data.get("features", [])])

candidate_name_cols = ["documentname", "nameeu", "namees", "name", "Nombre"]
name_col = next((c for c in candidate_name_cols if c in properties.columns), None)
if name_col is None or "restorationtype" not in properties.columns:
    raise KeyError("No se encontraron columnas de nombre/restorationtype en el GeoJSON")

def normalize_name(text):
    text = "" if pd.isna(text) else str(text)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = re.sub(r"\s+", " ", text).strip().lower()
    return text

geo_types = (
    properties[[name_col, "restorationtype"]]
    .dropna(subset=[name_col])
    .rename(columns={name_col: "nombre_geo"})
)
geo_types["nombre_key"] = geo_types["nombre_geo"].apply(normalize_name)
geo_types = (
    geo_types.groupby("nombre_key", as_index=False)["restorationtype"]
    .agg(lambda s: " | ".join(dict.fromkeys(str(v).strip() for v in s if pd.notna(v) and str(v).strip())))
)

df_restaurantes["nombre_key"] = df_restaurantes["Nombre"].apply(normalize_name)
restoration_map = geo_types.set_index("nombre_key")["restorationtype"]
df_restaurantes["restorationtype_match"] = df_restaurantes["nombre_key"].map(restoration_map)

mask_match = df_restaurantes["restorationtype_match"].notna()
df_restaurantes.loc[mask_match, "Tipo comida"] = df_restaurantes.loc[mask_match].apply(
    lambda row: concat_unique_types(row.get("Tipo comida"), row.get("restorationtype_match")),
    axis=1
)

df_restaurantes.drop(columns=["nombre_key", "restorationtype_match"], inplace=True)

n_rows_after = len(df_restaurantes)
if n_rows_after != n_rows_before:
    raise ValueError(f"El dataset se redujo de {n_rows_before} a {n_rows_after} filas")

In [62]:
df_restaurantes[["Nombre","Municipio","Descripcion", "Tipo de lugar", "Tipo comida", "WEB"]]

,Nombre,Municipio,Descripcion,Tipo de lugar,Tipo comida,WEB
0,Agorregi,San Sebastián,"El restaurante Agorregi, ubicado en el barrio ...",restaurantes,Restaurante,https://agorregi.com/
1,Aizian,Bilbao,Este moderno y acogedor restaurante fue diseña...,restaurantes,Restaurante,https://www.restaurante-aizian.com/
2,Akelarre,San Sebastián,Pedro Subijana desarrolla desde 1970 una cocin...,restaurantes,Restaurante,https://www.akelarre.net
3,Alameda,Hondarribia,La tercera generación es quien está a cargo de...,restaurantes,Restaurante,https://restaurantealameda.net/
4,Almiketxu,Bermeo,Es un caserío típico vasco y está regentado po...,restaurantes,Restaurante,https://almiketxu.com/
...,...,...,...,...,...,...
485,Quesería Soloitza,Ayala,Quesería Soloitza,"queseria, tiendas",Eusko Label,https://soloitza.com/
486,Larrañaga Gozotegia,Bergara,Repostería tradicional. De su obrador salen l...,tiendas,Denominación de Origen,NaN
487,Pastelería Sosoaga,Vitoria,"La pastelería López Sosoaga, abierta en 1868 p...",tiendas,Denominación de Origen,http://www.sosoaga.com
488,Pastelería La Peña Dulce,Vitoria,La Peña Dulce es una de las pastelerías de may...,tiendas,Denominación de Origen,NaN
489,Martina Zuricalday,Bilbao,NaN,tiendas,Denominación de Origen,http://www.martinazuricalday.com

In [63]:
export_path = "data/restaurantes_limpio_jose.csv"
df_restaurantes.to_csv(export_path, index=False)

## Estrellas

In [64]:
df_gastro = pd.read_csv("data/restaurantes_limpio_jose.csv")
df_gastro

,Unnamed: 0,Nombre,Descripcion,Dirección,Municipio,Provincia,Entorno,Email,Teléfono,WEB,...,Nivel precio,Michelin,Repsol,lat,lon,valoracion,num_resenas,url_imagen,Active,Patrocinado
0,0,Agorregi,"El restaurante Agorregi, ubicado en el barrio ...",NaN,San Sebastián,Guipúzcoa,"Costa Vasca,San Sebastián",agorregi@agorregi.com,943 22 43 28,https://agorregi.com/,...,Moderado,NaN,NaN,43.302405,-2.011846,4.6,571.0,https://places.googleapis.com/v1/places/ChIJFT...,1,0
1,1,Aizian,Este moderno y acogedor restaurante fue diseña...,NaN,Bilbao,Vizcaya,Bilbao,aizian@restaurante-aizian.com,944 28 00 39,https://www.restaurante-aizian.com/,...,Moderado,NaN,NaN,43.267519,-2.941807,4.7,435.0,https://places.googleapis.com/v1/places/ChIJde...,1,0
2,2,Akelarre,Pedro Subijana desarrolla desde 1970 una cocin...,NaN,San Sebastián,Guipúzcoa,San Sebastián,restaurante@akelarre.net,943 31 12 09,https://www.akelarre.net,...,Muy caro,NaN,NaN,43.307750,-2.043135,4.5,1925.0,https://places.googleapis.com/v1/places/ChIJXd...,1,0
3,3,Alameda,La tercera generación es quien está a cargo de...,NaN,Hondarribia,Guipúzcoa,Costa Vasca,info@restaurantealameda.net,943 64 27 89,https://restaurantealameda.net/,...,Caro,NaN,NaN,43.361242,-1.792691,4.6,1098.0,https://places.googleapis.com/v1/places/ChIJfb...,1,0
4,4,Almiketxu,Es un caserío típico vasco y está regentado po...,NaN,Bermeo,Vizcaya,Costa Vasca,almiketxu@gmail.com,946 88 09 25,https://almiketxu.com/,...,Caro,NaN,NaN,43.408905,-2.734229,4.6,1924.0,https://places.googleapis.com/v1/places/ChIJZ5...,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,765,Quesería Soloitza,Quesería Soloitza,NaN,Ayala,Álava,Montes y Valles vascos,info@soloitza.com,635 71 84 75,https://soloitza.com/,...,NaN,NaN,NaN,43.092827,-3.048182,5.0,45.0,https://places.googleapis.com/v1/places/ChIJmY...,1,0
486,767,Larrañaga Gozotegia,Repostería tradicional. De su obrador salen l...,NaN,Bergara,Guipúzcoa,Montes y Valles vascos,NaN,943 76 10 51,NaN,...,NaN,NaN,NaN,43.116464,-2.412943,4.6,70.0,https://places.googleapis.com/v1/places/ChIJLe...,1,0
487,772,Pastelería Sosoaga,"La pastelería López Sosoaga, abierta en 1868 p...",NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 25 85 73,http://www.sosoaga.com,...,NaN,NaN,NaN,42.842886,-2.668233,4.3,186.0,https://places.googleapis.com/v1/places/ChIJ1w...,1,0
488,773,Pastelería La Peña Dulce,La Peña Dulce es una de las pastelerías de may...,NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 13 26 37,NaN,...,NaN,NaN,NaN,42.851866,-2.673002,4.2,106.0,https://places.googleapis.com/v1/places/ChIJVc...,1,0
489,775,Martina Zuricalday,NaN,NaN,Bilbao,Vizcaya,Bilbao,NaN,944 43 57 96,http://www.martinazuricalday.com,...,Moderado,NaN,NaN,43.258907,-2.943496,4.2,372.0,https://places.googleapis.com/v1/places/ChIJsX...,1,0

In [69]:
restaurantesMichelin = [
  { "nombre": "Akelarre", "poblacion": "San Sebastián" },
  { "nombre": "Arzak", "poblacion": "San Sebastián" },
  { "nombre": "Azurmendi", "poblacion": "Larrabetzu" },
  { "nombre": "Martín Berasategui", "poblacion": "Lasarte-Oria" },
  { "nombre": "Amelia by Paulo Airaudo", "poblacion": "San Sebastián" },
  { "nombre": "Mugaritz", "poblacion": "Errenteria" },
  { "nombre": "Bakea", "poblacion": "Mungia" },
  { "nombre": "Islares", "poblacion": "Bilbao" },
  { "nombre": "Itzuli", "poblacion": "San Sebastián" },
  { "nombre": "La Revelía", "poblacion": "Amorebieta-Etxano" },
  { "nombre": "Alameda", "poblacion": "Hondarribia" },
  { "nombre": "Ama", "poblacion": "Tolosa" },
  { "nombre": "Andra Mari", "poblacion": "Galdakao" },
  { "nombre": "ARREA!", "poblacion": "Santa Cruz de Campezo" },
  { "nombre": "Boroa", "poblacion": "Amorebieta-Etxano" },
  { "nombre": "Elkano", "poblacion": "Getaria" },
  { "nombre": "Eneko", "poblacion": "Larrabetzu" },
  { "nombre": "Etxebarri", "poblacion": "Axpe" },
  { "nombre": "Garena", "poblacion": "Dima" },
  { "nombre": "iBAi", "poblacion": "San Sebastián" },
  { "nombre": "Kokotxa", "poblacion": "San Sebastián" },
  { "nombre": "Mina", "poblacion": "Bilbao" },
  { "nombre": "Nerua Guggenheim Bilbao", "poblacion": "Bilbao" },
  { "nombre": "Ola Martín Berasategui", "poblacion": "Bilbao" },
  { "nombre": "Txispa", "poblacion": "Axpe" },
  { "nombre": "Zarate", "poblacion": "Bilbao" }
];

In [70]:
import re
import unicodedata

def normalize_text(value):
    text = "" if pd.isna(value) else str(value)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = text.lower().strip()
    text = re.sub(r"\s+", " ", text)
    return text

def asignar_michelin(df, restaurantes_array):
    municipio_candidates = ["Poblacion", "Población", "Municipio", "municipio", "poblacion"]
    municipio_col = next((c for c in municipio_candidates if c in df.columns), None)
    if municipio_col is None:
        raise KeyError("No se encontro columna de poblacion/municipio en df_gastro")

    df = df.copy()
    df["Michelin"] = 0

    match_keys = {
        (normalize_text(item.get("nombre")), normalize_text(item.get("poblacion")))
        for item in restaurantes_array
    }

    df_keys = pd.Series(
        list(zip(df["Nombre"].map(normalize_text), df[municipio_col].map(normalize_text))),
        index=df.index
    )
    df.loc[df_keys.isin(match_keys), "Michelin"] = 1

    found_keys = set(df_keys[df["Michelin"] == 1].tolist())
    for item in restaurantes_array:
        key = (normalize_text(item.get("nombre")), normalize_text(item.get("poblacion")))
        estado = "ENCONTRADO" if key in found_keys else "NO ENCONTRADO"
        print(f"{estado}: {item.get('nombre')} - {item.get('poblacion')}")

    return df

df_gastro = asignar_michelin(df_gastro, restaurantesMichelin)
df_gastro[["Nombre", "Michelin"]].head()

ENCONTRADO: Akelarre - San Sebastián
ENCONTRADO: Arzak - San Sebastián
ENCONTRADO: Azurmendi - Larrabetzu
ENCONTRADO: Martín Berasategui - Lasarte-Oria
ENCONTRADO: Amelia by Paulo Airaudo - San Sebastián
NO ENCONTRADO: Mugaritz - Errenteria
NO ENCONTRADO: Bakea - Mungia
NO ENCONTRADO: Islares - Bilbao
NO ENCONTRADO: Itzuli - San Sebastián
ENCONTRADO: La Revelía - Amorebieta-Etxano
ENCONTRADO: Alameda - Hondarribia
ENCONTRADO: Ama - Tolosa
ENCONTRADO: Andra Mari - Galdakao
NO ENCONTRADO: ARREA! - Santa Cruz de Campezo
NO ENCONTRADO: Boroa - Amorebieta-Etxano
ENCONTRADO: Elkano - Getaria
ENCONTRADO: Eneko - Larrabetzu
NO ENCONTRADO: Etxebarri - Axpe
ENCONTRADO: Garena - Dima
NO ENCONTRADO: iBAi - San Sebastián
ENCONTRADO: Kokotxa - San Sebastián
ENCONTRADO: Mina - Bilbao
NO ENCONTRADO: Nerua Guggenheim Bilbao - Bilbao
ENCONTRADO: Ola Martín Berasategui - Bilbao
NO ENCONTRADO: Txispa - Axpe
ENCONTRADO: Zarate - Bilbao

      Nombre  Michelin
0   Agorregi         0
1     Aizian         0
2   Akelarre         1
3    Alameda         1
4  Almiketxu         0

In [ ]:
df_gastro[["Nombre", "Municipio", "Michelin"]]

                       Nombre      Municipio  Michelin
0                    Agorregi  San Sebastián         0
1                      Aizian         Bilbao         0
2                    Akelarre  San Sebastián         1
3                     Alameda    Hondarribia         1
4                   Almiketxu         Bermeo         0
..                        ...            ...       ...
485         Quesería Soloitza          Ayala         0
486       Larrañaga Gozotegia        Bergara         0
487        Pastelería Sosoaga        Vitoria         0
488  Pastelería La Peña Dulce        Vitoria         0
489        Martina Zuricalday         Bilbao         0

[490 rows x 3 columns]

In [74]:
restaurantes_repsol = [
    # --- GUIPÚZCOA ---
    {"nombre": "Akelarre", "poblacion": "San Sebastián"},
    {"nombre": "Arzak", "poblacion": "San Sebastián"},
    {"nombre": "Elkano", "poblacion": "Getaria"},
    {"nombre": "Martín Berasategui", "poblacion": "Lasarte-Oria"},
    {"nombre": "Mugaritz", "poblacion": "Errenteria"},
    {"nombre": "Alameda", "poblacion": "Hondarribia"},
    {"nombre": "AMA Tolosa", "poblacion": "Tolosa"},
    {"nombre": "Bodega Katxiña", "poblacion": "Orio"},
    {"nombre": "Casa Julián – Matías Gorrotxategi", "poblacion": "Tolosa"},
    {"nombre": "Casa Urola", "poblacion": "San Sebastián"},
    {"nombre": "Hika Gastronomiko", "poblacion": "Villabona"},
    {"nombre": "Kaia-Kaipe", "poblacion": "Getaria"},
    {"nombre": "Kokotxa", "poblacion": "San Sebastián"},
    {"nombre": "Laia Erretegia", "poblacion": "Hondarribia"},
    {"nombre": "Mirador de Ulía", "poblacion": "San Sebastián"},
    {"nombre": "Narru", "poblacion": "San Sebastián"},
    {"nombre": "Rekondo", "poblacion": "San Sebastián"},
    {"nombre": "Aiten Etxe", "poblacion": "Zarautz"},
    {"nombre": "Araneta", "poblacion": "Zestoa"},
    {"nombre": "Asador Landa", "poblacion": "Mendaro"},
    {"nombre": "Asador Nicolás", "poblacion": "Tolosa"},
    {"nombre": "Astelena 1997", "poblacion": "San Sebastián"},
    {"nombre": "Bailara", "poblacion": "Bidania-Goiatz"},
    {"nombre": "Casa Cámara", "poblacion": "Pasaia"},
    {"nombre": "Espazio Oteiza-Akelarre", "poblacion": "San Sebastián"},
    {"nombre": "Etxeberri", "poblacion": "Zumárraga"},
    {"nombre": "Fagollaga", "poblacion": "Hernani"},
    {"nombre": "Ganbara", "poblacion": "San Sebastián"},
    {"nombre": "Hamarratz", "poblacion": "Zumaia"},
    {"nombre": "Iriarte", "poblacion": "Berrobi"},
    {"nombre": "Itzuli", "poblacion": "Donostia-San Sebastián"},
    {"nombre": "Kirkilla Enea", "poblacion": "Zarautz"},
    {"nombre": "Muka", "poblacion": "San Sebastián"},
    {"nombre": "Sukaldean Aitor Santamaria", "poblacion": "Donostia-San Sebastián"},
    {"nombre": "Sutan", "poblacion": "Hondarribia"},
    {"nombre": "Zazpi STM", "poblacion": "San Sebastián"},
    {"nombre": "Zelai Txiki", "poblacion": "San Sebastián"},

    # --- VIZCAYA ---
    {"nombre": "Azurmendi", "poblacion": "Larrabetzu"},
    {"nombre": "Etxebarri", "poblacion": "Atxondo"},
    {"nombre": "Nerua Guggenheim Bilbao", "poblacion": "Bilbao"},
    {"nombre": "Andra Mari", "poblacion": "Galdakao"},
    {"nombre": "Atelier Etxanobe", "poblacion": "Bilbao"},
    {"nombre": "Bakea", "poblacion": "Mungia"},
    {"nombre": "Boroa", "poblacion": "Amorebieta-Etxano"},
    {"nombre": "Garena", "poblacion": "Dima"},
    {"nombre": "Mina", "poblacion": "Bilbao"},
    {"nombre": "Zarate", "poblacion": "Bilbao"},
    {"nombre": "Aitor Rauleaga", "poblacion": "Bilbao"},
    {"nombre": "Amaren", "poblacion": "Bilbao"},
    {"nombre": "Aretxondo", "poblacion": "Galdakao"},
    {"nombre": "Baserri Maitea", "poblacion": "Forua"},
    {"nombre": "Casa Garras", "poblacion": "Valle de Carranza"},
    {"nombre": "El Paladar by Zuriñe García", "poblacion": "Portugalete"},
    {"nombre": "Eneko", "poblacion": "Larrabetzu"},
    {"nombre": "Gotzon Jatetxea", "poblacion": "Bakio"},
    {"nombre": "Horma Ondo", "poblacion": "Larrabetzu"},
    {"nombre": "Islares", "poblacion": "Bilbao"},
    {"nombre": "Jauregibarria", "poblacion": "Amorebieta"},
    {"nombre": "Kuma", "poblacion": "Bilbao"},
    {"nombre": "La Despensa del Etxanobe", "poblacion": "Bilbao"},
    {"nombre": "Mendi Goikoa Bekoa", "poblacion": "Atxondo"},
    {"nombre": "Ola Martín Berasategui", "poblacion": "Bilbao"},
    {"nombre": "Porrue", "poblacion": "Bilbao"},
    {"nombre": "Remenetxe", "poblacion": "Muxica"},
    {"nombre": "Tamarises Izarra", "poblacion": "Getxo"},
    {"nombre": "Txispa", "poblacion": "Atxondo"},
    {"nombre": "Yandiola", "poblacion": "Bilbao"},

    # --- ÁLAVA ---
    {"nombre": "Arrea!", "poblacion": "Santa Cruz de Campezo"},
    {"nombre": "Bideko", "poblacion": "Lezama"},
    {"nombre": "Karmine", "poblacion": "Vitoria-Gasteiz"},
    {"nombre": "KEA Basque Fine Food", "poblacion": "Vitoria-Gasteiz"},
    {"nombre": "Kromatiko", "poblacion": "Vitoria-Gasteiz"},
    {"nombre": "Marqués de Riscal", "poblacion": "Elciego"},
    {"nombre": "Tierra y vino", "poblacion": "Samaniego"},
    {"nombre": "Zaldiarán", "poblacion": "Vitoria-Gasteiz"}
]

In [75]:
import re
import unicodedata

def normalize_text(value):
    text = "" if pd.isna(value) else str(value)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = text.lower().strip()
    text = re.sub(r"\s+", " ", text)
    return text

def asignar_Repsol(df, restaurantes_array):
    municipio_candidates = ["Poblacion", "Población", "Municipio", "municipio", "poblacion"]
    municipio_col = next((c for c in municipio_candidates if c in df.columns), None)
    if municipio_col is None:
        raise KeyError("No se encontro columna de poblacion/municipio en df_gastro")

    df = df.copy()
    df["Repsol"] = 0

    match_keys = {
        (normalize_text(item.get("nombre")), normalize_text(item.get("poblacion")))
        for item in restaurantes_array
    }

    df_keys = pd.Series(
        list(zip(df["Nombre"].map(normalize_text), df[municipio_col].map(normalize_text))),
        index=df.index
    )
    df.loc[df_keys.isin(match_keys), "Repsol"] = 1

    found_keys = set(df_keys[df["Repsol"] == 1].tolist())
    for item in restaurantes_array:
        key = (normalize_text(item.get("nombre")), normalize_text(item.get("poblacion")))
        estado = "ENCONTRADO" if key in found_keys else "NO ENCONTRADO"
        print(f"{estado}: {item.get('nombre')} - {item.get('poblacion')}")

    return df

df_gastro = asignar_Repsol(df_gastro, restaurantes_repsol)
df_gastro[["Nombre", "Repsol"]].head()

ENCONTRADO: Akelarre - San Sebastián
ENCONTRADO: Arzak - San Sebastián
ENCONTRADO: Elkano - Getaria
ENCONTRADO: Martín Berasategui - Lasarte-Oria
NO ENCONTRADO: Mugaritz - Errenteria
ENCONTRADO: Alameda - Hondarribia
NO ENCONTRADO: AMA Tolosa - Tolosa
ENCONTRADO: Bodega Katxiña - Orio
NO ENCONTRADO: Casa Julián – Matías Gorrotxategi - Tolosa
ENCONTRADO: Casa Urola - San Sebastián
NO ENCONTRADO: Hika Gastronomiko - Villabona
NO ENCONTRADO: Kaia-Kaipe - Getaria
ENCONTRADO: Kokotxa - San Sebastián
ENCONTRADO: Laia Erretegia - Hondarribia
ENCONTRADO: Mirador de Ulía - San Sebastián
ENCONTRADO: Narru - San Sebastián
ENCONTRADO: Rekondo - San Sebastián
NO ENCONTRADO: Aiten Etxe - Zarautz
NO ENCONTRADO: Araneta - Zestoa
NO ENCONTRADO: Asador Landa - Mendaro
ENCONTRADO: Asador Nicolás - Tolosa
NO ENCONTRADO: Astelena 1997 - San Sebastián
NO ENCONTRADO: Bailara - Bidania-Goiatz
ENCONTRADO: Casa Cámara - Pasaia
NO ENCONTRADO: Espazio Oteiza-Akelarre - San Sebastián
NO ENCONTRADO: Etxeberri - Zumárraga
ENCONTRADO: Fagollaga - Hernani
ENCONTRADO: Ganbara - San Sebastián
NO ENCONTRADO: Hamarratz - Zumaia
ENCONTRADO: Iriarte - Berrobi
NO ENCONTRADO: Itzuli - Donostia-San Sebastián
NO ENCONTRADO: Kirkilla Enea - Zarautz
ENCONTRADO: Muka - San Sebastián
NO ENCONTRADO: Sukaldean Aitor Santamaria - Donostia-San Sebastián
NO ENCONTRADO: Sutan - Hondarribia
NO ENCONTRADO: Zazpi STM - San Sebastián
ENCONTRADO: Zelai Txiki - San Sebastián
ENCONTRADO: Azurmendi - Larrabetzu
ENCONTRADO: Etxebarri - Atxondo
NO ENCONTRADO: Nerua Guggenheim Bilbao - Bilbao
ENCONTRADO: Andra Mari - Galdakao
ENCONTRADO: Atelier Etxanobe - Bilbao
NO ENCONTRADO: Bakea - Mungia
NO ENCONTRADO: Boroa - Amorebieta-Etxano
ENCONTRADO: Garena - Dima
ENCONTRADO: Mina - Bilbao
ENCONTRADO: Zarate - Bilbao
ENCONTRADO: Aitor Rauleaga - Bilbao
NO ENCONTRADO: Amaren - Bilbao
ENCONTRADO: Aretxondo - Galdakao
ENCONTRADO: Baserri Maitea - Forua
ENCONTRADO: Casa Garras - Valle de Carranza
NO ENCONTRADO: El Paladar by Zuriñe García - Portugalete
ENCONTRADO: Eneko - Larrabetzu
NO ENCONTRADO: Gotzon Jatetxea - Bakio
ENCONTRADO: Horma Ondo - Larrabetzu
NO ENCONTRADO: Islares - Bilbao
NO ENCONTRADO: Jauregibarria - Amorebieta
NO ENCONTRADO: Kuma - Bilbao
NO ENCONTRADO: La Despensa del Etxanobe - Bilbao
NO ENCONTRADO: Mendi Goikoa Bekoa - Atxondo
ENCONTRADO: Ola Martín Berasategui - Bilbao
ENCONTRADO: Porrue - Bilbao
NO ENCONTRADO: Remenetxe - Muxica
NO ENCONTRADO: Tamarises Izarra - Getxo
NO ENCONTRADO: Txispa - Atxondo
ENCONTRADO: Yandiola - Bilbao
NO ENCONTRADO: Arrea! - Santa Cruz de Campezo
NO ENCONTRADO: Bideko - Lezama
NO ENCONTRADO: Karmine - Vitoria-Gasteiz
NO ENCONTRADO: KEA Basque Fine Food - Vitoria-Gasteiz
NO ENCONTRADO: Kromatiko - Vitoria-Gasteiz
ENCONTRADO: Marqués de Riscal - Elciego
NO ENCONTRADO: Tierra y vino - Samaniego
NO ENCONTRADO: Zaldiarán - Vitoria-Gasteiz

      Nombre  Repsol
0   Agorregi       0
1     Aizian       0
2   Akelarre       1
3    Alameda       1
4  Almiketxu       0

In [76]:
df_gastro[["Nombre", "Municipio", "Michelin", "Repsol"]]

                       Nombre      Municipio  Michelin  Repsol
0                    Agorregi  San Sebastián         0       0
1                      Aizian         Bilbao         0       0
2                    Akelarre  San Sebastián         1       1
3                     Alameda    Hondarribia         1       1
4                   Almiketxu         Bermeo         0       0
..                        ...            ...       ...     ...
485         Quesería Soloitza          Ayala         0       0
486       Larrañaga Gozotegia        Bergara         0       0
487        Pastelería Sosoaga        Vitoria         0       0
488  Pastelería La Peña Dulce        Vitoria         0       0
489        Martina Zuricalday         Bilbao         0       0

[490 rows x 4 columns]

In [79]:
export_path = "data/restaurantes_limpio_jose.csv"
df_gastro.to_csv(export_path, index=False)

In [84]:
df_gastronomia = pd.read_csv("data/restaurantes_limpio_jose_michelin.csv")
df_gastronomia

,Unnamed: 0,Nombre,Descripcion,Dirección,Municipio,Provincia,Entorno,Email,Teléfono,WEB,...,Nivel precio,Michelin,Repsol,lat,lon,valoracion,num_resenas,url_imagen,Active,Patrocinado
0,0,Agorregi,"El restaurante Agorregi, ubicado en el barrio ...",NaN,San Sebastián,Guipúzcoa,"Costa Vasca,San Sebastián",agorregi@agorregi.com,943 22 43 28,https://agorregi.com/,...,Moderado,0,0,43.302405,-2.011846,4.6,571.0,https://places.googleapis.com/v1/places/ChIJFT...,1,0
1,1,Aizian,Este moderno y acogedor restaurante fue diseña...,NaN,Bilbao,Vizcaya,Bilbao,aizian@restaurante-aizian.com,944 28 00 39,https://www.restaurante-aizian.com/,...,Moderado,0,0,43.267519,-2.941807,4.7,435.0,https://places.googleapis.com/v1/places/ChIJde...,1,0
2,2,Akelarre,Pedro Subijana desarrolla desde 1970 una cocin...,NaN,San Sebastián,Guipúzcoa,San Sebastián,restaurante@akelarre.net,943 31 12 09,https://www.akelarre.net,...,Muy caro,1,1,43.307750,-2.043135,4.5,1925.0,https://places.googleapis.com/v1/places/ChIJXd...,1,0
3,3,Alameda,La tercera generación es quien está a cargo de...,NaN,Hondarribia,Guipúzcoa,Costa Vasca,info@restaurantealameda.net,943 64 27 89,https://restaurantealameda.net/,...,Caro,1,1,43.361242,-1.792691,4.6,1098.0,https://places.googleapis.com/v1/places/ChIJfb...,1,0
4,4,Almiketxu,Es un caserío típico vasco y está regentado po...,NaN,Bermeo,Vizcaya,Costa Vasca,almiketxu@gmail.com,946 88 09 25,https://almiketxu.com/,...,Caro,0,0,43.408905,-2.734229,4.6,1924.0,https://places.googleapis.com/v1/places/ChIJZ5...,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,765,Quesería Soloitza,Quesería Soloitza,NaN,Ayala,Álava,Montes y Valles vascos,info@soloitza.com,635 71 84 75,https://soloitza.com/,...,NaN,0,0,43.092827,-3.048182,5.0,45.0,https://places.googleapis.com/v1/places/ChIJmY...,1,0
486,767,Larrañaga Gozotegia,Repostería tradicional. De su obrador salen l...,NaN,Bergara,Guipúzcoa,Montes y Valles vascos,NaN,943 76 10 51,NaN,...,NaN,0,0,43.116464,-2.412943,4.6,70.0,https://places.googleapis.com/v1/places/ChIJLe...,1,0
487,772,Pastelería Sosoaga,"La pastelería López Sosoaga, abierta en 1868 p...",NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 25 85 73,http://www.sosoaga.com,...,NaN,0,0,42.842886,-2.668233,4.3,186.0,https://places.googleapis.com/v1/places/ChIJ1w...,1,0
488,773,Pastelería La Peña Dulce,La Peña Dulce es una de las pastelerías de may...,NaN,Vitoria,Álava,Vitoria-Gasteiz,NaN,945 13 26 37,NaN,...,NaN,0,0,42.851866,-2.673002,4.2,106.0,https://places.googleapis.com/v1/places/ChIJVc...,1,0
489,775,Martina Zuricalday,NaN,NaN,Bilbao,Vizcaya,Bilbao,NaN,944 43 57 96,http://www.martinazuricalday.com,...,Moderado,0,0,43.258907,-2.943496,4.2,372.0,https://places.googleapis.com/v1/places/ChIJsX...,1,0

In [85]:
# vamos a hacer un replace de hppt por https en la columna WEB para evitar problemas de validacion de url
df_gastronomia["WEB"] = df_gastronomia["WEB"].str.replace(r"^hppt://", "https://", regex=True)

In [83]:
load_dotenv()
API_KEY = os.getenv("API_KEY_MAPS")

In [90]:
def safe_json(response, context="request"):
    """Devuelve JSON seguro; imprime errores de estado/parsing y retorna None si falla."""
    try:
        response.raise_for_status()
    except requests.HTTPError as exc:
        print(f"[HTTP {response.status_code}] {context}: {exc}")
        return None

    try:
        return response.json()
    except ValueError:
        print(f"[JSON ERROR] {context}: respuesta no valida")
        return None


def search_place_id(nombre, municipio, lat, log, web, api_key):
    """Busca Place ID en Google Places. Primero por nombre+municipio y luego por web."""
    payload = {"textQuery": f"{nombre}, {municipio}"}
    if pd.notna(lat) and pd.notna(log):
        payload["locationBias"] = {
            "circle": {
                "center": {"latitude": float(lat), "longitude": float(log)},
                "radius": 500.0
            }
        }

    r = requests.post(
        "https://places.googleapis.com/v1/places:searchText",
        json=payload,
        headers={
            "Content-Type": "application/json",
            "X-Goog-Api-Key": api_key,
            "X-Goog-FieldMask": "places.id"
        },
        timeout=20
    )
    places = (safe_json(r, f"search '{nombre}'") or {}).get("places", [])

    if not places and web:
        print(f"[FALLBACK web] '{nombre}' -> {web}")
        r2 = requests.post(
            "https://places.googleapis.com/v1/places:searchText",
            json={"textQuery": str(web)},
            headers={
                "Content-Type": "application/json",
                "X-Goog-Api-Key": api_key,
                "X-Goog-FieldMask": "places.id"
            },
            timeout=20
        )
        places = (safe_json(r2, f"search web '{nombre}'") or {}).get("places", [])

    return places[0]["id"] if places else None


def get_place_details(place_id, api_key):
    """Obtiene solo la direccion formateada de un Place ID."""
    r = requests.get(
        f"https://places.googleapis.com/v1/places/{place_id}",
        headers={
            "X-Goog-Api-Key": api_key,
            "X-Goog-FieldMask": "formattedAddress"
        },
        timeout=20
    )
    return safe_json(r, f"details '{place_id}'")


def enrich_dataframe(df, api_key, limit=None):
    """Enriquece SOLO la columna Direccion usando Google Places API."""
    if not api_key:
        raise ValueError("API_KEY_MAPS no esta configurada")

    df = df.copy()
    df["Dirección"] = pd.Series(df.get("Dirección", ""), index=df.index, dtype="object")

    subset = df.head(limit) if limit else df
    cont_ok, cont_ko = 0, 0

    for idx, row in subset.iterrows():
        nombre = row.get("Nombre")
        municipio = row.get("Municipio")
        lat = row.get("lat")
        log = row.get("log")
        web = row.get("WEB") if pd.notna(row.get("WEB")) and str(row.get("WEB")).strip() else None

        place_id = search_place_id(nombre, municipio, lat, log, web, api_key)
        if not place_id:
            print(f"[SKIP] sin resultados para '{nombre}'")
            continue

        details = get_place_details(place_id, api_key)
        if not details:
            print(f"[SKIP] sin direccion para '{nombre}'")
            cont_ko += 1
            continue

        df.at[idx, "Dirección"] = details.get("formattedAddress", "")
        cont_ok += 1
        print(f"[OK] '{nombre}' -> {df.at[idx, 'Dirección']} (ok: {cont_ok})")

    print("\n--- RESUMEN ---")
    print(f"Direcciones enriquecidas: {cont_ok} / {len(subset)} | Fallos: {cont_ko}")
    return df

In [ ]:
df_gastronomia_direc = enrich_dataframe(df_gastronomia, API_KEY)

In [91]:
df_gastronomia_test = enrich_dataframe(df_gastronomia, API_KEY, limit=5)
df_gastronomia_test[["Nombre", "Municipio", "Dirección"]].head(5)

[OK] 'Agorregi' -> Portuetxe K., 14, 20018 Donostia / San Sebastián, Gipuzkoa, Spain (ok: 1)
[OK] 'Aizian' -> Leizaola Lehendakariaren Kalea, 29, Abando, 48001 Bilbao, Bizkaia, Spain (ok: 2)
[OK] 'Akelarre' -> Padre Orkolaga Ibilbidea, 56, 20008 Donostia / San Sebastián, Gipuzkoa, Spain (ok: 3)
[OK] 'Alameda' -> Minasoroeta Kalea, 1, 20280, Gipuzkoa, Spain (ok: 4)
[OK] 'Almiketxu' -> Almike Auzoa, 8, 48370 Bermeo, Bizkaia, Spain (ok: 5)

--- RESUMEN ---
Direcciones enriquecidas: 5 / 5 | Fallos: 0

      Nombre      Municipio                                          Dirección
0   Agorregi  San Sebastián  Portuetxe K., 14, 20018 Donostia / San Sebasti...
1     Aizian         Bilbao  Leizaola Lehendakariaren Kalea, 29, Abando, 48...
2   Akelarre  San Sebastián  Padre Orkolaga Ibilbidea, 56, 20008 Donostia /...
3    Alameda    Hondarribia       Minasoroeta Kalea, 1, 20280, Gipuzkoa, Spain
4  Almiketxu         Bermeo      Almike Auzoa, 8, 48370 Bermeo, Bizkaia, Spain